### ISSUE TITLE
Conflict with Sparkfun Alpha Library

### ISSUE THREAD

**Issue by sylgeist** [sparkfun/SparkFun_Qwiic_Button_Arduino_Library#5]
### Subject of the issue
Warning when including both Qwiic button and Alphanumeric libraries

### Your workbench
Independent of board. Tested with Artemis ATP and Redboard
Arduino 1.8.13 on MacOS 12.0.1
Qwiic Button 2.0.5
Qwiic Alphanumeric 2.2.5

### Steps to reproduce
If you have both:
```
#include "SparkFun_Alphanumeric_Display.h"
#include "SparkFun_Qwiic_Button.h"
```

in a project you receive a warning on compilation (see below)

### Expected behavior
Should compile without warning

### Actual behavior
```
In file included from /Documents/Arduino/ShuttleOS/ShuttleOS.ino:16:
/Documents/Arduino/libraries/SparkFun_Qwiic_Button_and_Qwiic_Switch_Library/src/SparkFun_Qwiic_Button.h:29: warning: "DEFAULT_ADDRESS" redefined
 #define DEFAULT_ADDRESS 0x6F //default I2C address of the button
 
In file included from /Documents/Arduino/ShuttleOS/ShuttleOS.ino:14:
/Documents/Arduino/libraries/SparkFun_Qwiic_Alphanumeric_Display_Arduino_Library/src/SparkFun_Alphanumeric_Display.h:32: note: this is the location of the previous definition
 #define DEFAULT_ADDRESS 0x70 // Default I2C address when A0, A1 are floating
```

**Comment by PaulZC** [comment]
Resolved in v2.0.6 - thank you for reporting and apologies for the delay!

Paul
